"""Phase 3: verification checks, face matches, document review

Revision ID: 0003_verification
Revises: 0002_documents
Create Date: 2026-08-04 23:19:23.275205
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.types  # TZDateTime, referenced by the column definitions below

revision: str = '0003_verification'
down_revision: Union[str, None] = '0002_documents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('photo_document_id', sa.Uuid(), nullable=True),
    sa.Column('id_document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('matched', 'not_matched', 'no_face_in_photo', 'no_face_in_id', 'multiple_faces_in_photo', 'error', name='face_match_status'), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('performed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_matches_created_at'), 'face_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_face_matches_employee_id'), 'face_matches', ['employee_id'], unique=False)
    op.create_index(op.f('ix_face_matches_id_document_id'), 'face_matches', ['id_document_id'], unique=False)
    op.create_index(op.f('ix_face_matches_photo_document_id'), 'face_matches', ['photo_document_id'], unique=False)
    op.create_index(op.f('ix_face_matches_status'), 'face_matches', ['status'], unique=False)
    op.create_table('verification_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sa.Enum('aadhaar', 'pan', name='verification_check_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'error', name='verification_status'), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('masked_number', sa.String(length=32), nullable=True),
    sa.Column('name_similarity', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('performed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_checks_check_type'), 'verification_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_verification_checks_created_at'), 'verification_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_checks_document_id'), 'verification_checks', ['document_id'], unique=False)
    op.create_index(op.f('ix_verification_checks_employee_id'), 'verification_checks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_verification_checks_reference_id'), 'verification_checks', ['reference_id'], unique=False)
    op.create_index(op.f('ix_verification_checks_status'), 'verification_checks', ['status'], unique=False)
    op.add_column('documents', sa.Column('reviewed_by_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('reviewed_at', app.core.types.TZDateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # Named explicitly: autogenerate emits an anonymous constraint, which the
    # downgrade below then cannot drop.
    op.create_foreign_key(
        'fk_documents_reviewed_by_id_users',
        'documents', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documents_reviewed_by_id_users', 'documents', type_='foreignkey')
    op.drop_column('documents', 'rejection_reason')
    op.drop_column('documents', 'reviewed_at')
    op.drop_column('documents', 'reviewed_by_id')
    op.drop_index(op.f('ix_verification_checks_status'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_reference_id'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_employee_id'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_document_id'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_created_at'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_check_type'), table_name='verification_checks')
    op.drop_table('verification_checks')
    op.drop_index(op.f('ix_face_matches_status'), table_name='face_matches')
    op.drop_index(op.f('ix_face_matches_photo_document_id'), table_name='face_matches')
    op.drop_index(op.f('ix_face_matches_id_document_id'), table_name='face_matches')
    op.drop_index(op.f('ix_face_matches_employee_id'), table_name='face_matches')
    op.drop_index(op.f('ix_face_matches_created_at'), table_name='face_matches')
    op.drop_table('face_matches')
    # ### end Alembic commands ###

    # Autogenerate leaves its enum types behind on downgrade; drop them so the
    # migration fully reverses (matches 0001/0002).
    bind = op.get_bind()
    for enum_name in ("face_match_status", "verification_status", "verification_check_type"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
