"""Phase 4: task templates, assignment rules, employee tasks

Revision ID: 0004_tasks
Revises: 0003_verification
Create Date: 2026-08-05 00:20:39.268686
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.types  # TZDateTime, referenced by the column definitions below


revision: str = '0004_tasks'
down_revision: Union[str, None] = '0003_verification'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# `document_type` already exists (created by 0002); reference it without
# attempting to CREATE TYPE a second time.
document_type_ref = postgresql.ENUM(
    'aadhaar', 'pan', 'resume', 'certificate', 'photo', 'other',
    name='document_type',
    create_type=False,
).with_variant(
    sa.Enum(
        'aadhaar', 'pan', 'resume', 'certificate', 'photo', 'other',
        name='document_type',
    ),
    'sqlite',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_rules_department'), 'assignment_rules', ['department'], unique=False)
    op.create_index(op.f('ix_assignment_rules_is_active'), 'assignment_rules', ['is_active'], unique=False)
    op.create_table('task_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('task', 'training', 'document_checklist', 'policy_acknowledgement', name='task_category'), nullable=False),
    sa.Column('default_due_days', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('resource_url', sa.String(length=512), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('required_document_type', document_type_ref, nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_templates_category'), 'task_templates', ['category'], unique=False)
    op.create_index(op.f('ix_task_templates_code'), 'task_templates', ['code'], unique=True)
    op.create_index(op.f('ix_task_templates_is_active'), 'task_templates', ['is_active'], unique=False)
    op.create_table('assignment_rule_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('due_days_override', sa.Integer(), nullable=True),
    sa.Column('is_mandatory_override', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['assignment_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'template_id', name='uq_rule_template')
    )
    op.create_index(op.f('ix_assignment_rule_items_rule_id'), 'assignment_rule_items', ['rule_id'], unique=False)
    op.create_index(op.f('ix_assignment_rule_items_template_id'), 'assignment_rule_items', ['template_id'], unique=False)
    op.create_table('employee_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('task', 'training', 'document_checklist', 'policy_acknowledgement', name='task_category'), nullable=False),
    sa.Column('resource_url', sa.String(length=512), nullable=True),
    sa.Column('required_document_type', document_type_ref, nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'waived', name='task_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', app.core.types.TZDateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Uuid(), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.types.TZDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['assignment_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['task_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'template_id', name='uq_employee_template')
    )
    op.create_index(op.f('ix_employee_tasks_category'), 'employee_tasks', ['category'], unique=False)
    op.create_index(op.f('ix_employee_tasks_due_date'), 'employee_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_employee_tasks_employee_id'), 'employee_tasks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_tasks_status'), 'employee_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_employee_tasks_template_id'), 'employee_tasks', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_tasks_template_id'), table_name='employee_tasks')
    op.drop_index(op.f('ix_employee_tasks_status'), table_name='employee_tasks')
    op.drop_index(op.f('ix_employee_tasks_employee_id'), table_name='employee_tasks')
    op.drop_index(op.f('ix_employee_tasks_due_date'), table_name='employee_tasks')
    op.drop_index(op.f('ix_employee_tasks_category'), table_name='employee_tasks')
    op.drop_table('employee_tasks')
    op.drop_index(op.f('ix_assignment_rule_items_template_id'), table_name='assignment_rule_items')
    op.drop_index(op.f('ix_assignment_rule_items_rule_id'), table_name='assignment_rule_items')
    op.drop_table('assignment_rule_items')
    op.drop_index(op.f('ix_task_templates_is_active'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_code'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_category'), table_name='task_templates')
    op.drop_table('task_templates')
    op.drop_index(op.f('ix_assignment_rules_is_active'), table_name='assignment_rules')
    op.drop_index(op.f('ix_assignment_rules_department'), table_name='assignment_rules')
    op.drop_table('assignment_rules')
    # ### end Alembic commands ###

    # Autogenerate does not clean up the enum types it created.
    bind = op.get_bind()
    for enum_name in ("task_status", "task_category"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
