"""Phase 7: session metadata

Revision ID: 0007_session_metadata
Revises: 0006_notifications
Create Date: 2026-08-08 22:24:30.561795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.types  # TZDateTime, referenced by the column definitions below


revision: str = '0007_session_metadata'
down_revision: Union[str, None] = '0006_notifications'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('refresh_tokens', sa.Column('last_used_at', app.core.types.TZDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    # ### end Alembic commands ###
