"""Phase 5: persist chat error

Revision ID: 0008_chat_error_message
Revises: 0007_session_metadata
Create Date: 2026-08-23 01:47:10.841087
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0008_chat_error_message'
down_revision: Union[str, None] = '0007_session_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'error_message')
    # ### end Alembic commands ###
